// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMdiK7RUNNKC3akjeoNqc5cEyFYmF3BE0',
    appId: '1:758211228516:web:8256f0d50d611e45320071',
    messagingSenderId: '758211228516',
    projectId: 'todoist-38ac4',
    authDomain: 'todoist-38ac4.firebaseapp.com',
    storageBucket: 'todoist-38ac4.appspot.com',
    measurementId: 'G-91VC8DNYL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOD2ImPWw9FG6kOzYeDXKEMIWZU6rM3_4',
    appId: '1:758211228516:android:719c79a7c4b783d3320071',
    messagingSenderId: '758211228516',
    projectId: 'todoist-38ac4',
    storageBucket: 'todoist-38ac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa-jpfUyLvXD9K-9WSIcvjSy4rIS4iSt8',
    appId: '1:758211228516:ios:1499a13c63989572320071',
    messagingSenderId: '758211228516',
    projectId: 'todoist-38ac4',
    storageBucket: 'todoist-38ac4.appspot.com',
    iosClientId: '758211228516-8f701o3g7nsorjuo3ckktcqdbhiih1ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa-jpfUyLvXD9K-9WSIcvjSy4rIS4iSt8',
    appId: '1:758211228516:ios:1499a13c63989572320071',
    messagingSenderId: '758211228516',
    projectId: 'todoist-38ac4',
    storageBucket: 'todoist-38ac4.appspot.com',
    iosClientId: '758211228516-8f701o3g7nsorjuo3ckktcqdbhiih1ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
